Repository Sanofi-IADC/konviw, pull requests merged in 2022-07, with the labels that each got.

#425 fix: WEB-132 Dark theme's special stylesheet
  src/assets/scss/_dark-theme.scss
  src/assets/scss/custom.scss
  src/assets/scss/iadc/_dark-theme.scss
  src/assets/scss/iadc/custom.scss
Labels: deployed

#426 fix: WEB-196 Panel style to match Confluence
  cypress.json
  src/assets/scss/_macro-info-panel.scss
  src/assets/scss/iadc/_macro-info-panel.scss
  tests/e2e/cypress/integration/__image_snapshots__/Info panels  match the whole page #0.png
  tests/e2e/cypress/integration/__image_snapshots__/Layouts Three Columns  match the whole page #0.png
  tests/e2e/cypress/integration/__image_snapshots__/Tables  match the whole page #0.png
  tests/e2e/cypress/integration/info-panels.spec.ts
Labels: deployed

#430 Bugfix/web 206
  src/assets/scss/_tables.scss
  src/assets/scss/iadc/_tables.scss
  tests/e2e/cypress/integration/__image_snapshots__/Tables  match the whole page #0.png
Labels: deployed

#428 Feature: header image and header emoji
  src/confluence/confluence.service.ts
  src/context/context.service.ts
  src/proxy-page/steps/addHeaderTitle.ts
  tests/unit/steps/addHeaderTitle.spec.ts
Labels: deployed

#433 Bugfix: narrow confluence-jim-macro selector to include jira-table only
  src/proxy-page/steps/addJira.ts
  tests/unit/steps/addJira.spec.ts
Labels: bug, deployed

#432 Feature: WEB-261 render pages by version
  src/confluence/confluence.service.ts
  src/proxy-api/proxy-api.service.ts
  src/proxy-page/proxy-page.controller.ts
  src/proxy-page/proxy-page.service.ts
  src/proxy-page/proxy-page.validation.dto.ts
  tests/unit/proxy-api/proxy-api.service.spec.ts
Labels: enhancement, deployed

#435 fix: WEB-178 fixed background colors
  src/assets/scss/_tables.scss
  src/assets/scss/iadc/_tables.scss
  src/proxy-page/proxy-page.service.ts
  src/proxy-page/steps/fixTableBackground.ts
Labels: deployed

#431 fix: WEB-207 SVG images now have the proper src, width and alignment
  .eslintrc.js
  .prettierrc
  package.json
  src/proxy-page/proxy-page.service.ts
  src/proxy-page/steps/fixSVG.ts
  tests/unit/steps/fixSVG.spec.ts
Labels: bug, deployed

#436 WEB-211 Update Jira issue references
  src/jira/jira.service.ts
  src/proxy-page/steps/addJira.ts
  tests/unit/steps/addJira.spec.ts
Labels: deployed

#438 fix: comment fixSVG import
  src/proxy-page/proxy-page.service.ts
Labels: deployed
